### ISSUE TITLE
How to install from source codes

### ISSUE THREAD

**Issue by hxwork** [stkevintan/xmlya#1]
Hello,

Thanks for your open-source codes. I am not familiar with packaging vscode extensions. Could you offer some commands for installing or packaging ".vsix" format file from source codes?

**Comment by stkevintan** [comment]
Hi Hao, glad to see you are interested in my work. actually the extension is still work in progress.  the latest branch is `refactor`, I am facing a hard problem about how to implement the login features. will publish the extension to vs-code official store once I resolve it.

**Comment by hxwork** [comment]
Thanks for your reply, I am looking forward to your final version.
